/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Header: React.FC = () => {
  return (
    <header className='self-center text-4xl font-bold text-zinc-900'>
      SAFEGUARD YOUR BUSINESS WITH ALL-IN-ONE CYBERSECURITY
    </header>
  );
};

export default Header;
